CREATE TABLE CUSTOMER(
    ID_CUSTOMER NUMERIC(6) NOT NULL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    SECOND_NAME VARCHAR(64) NOT NULL,
    BUSINESS_NAME VARCHAR(64) NOT NULL,
    PHONE VARCHAR(32) NOT NULL,
    ADDRESS VARCHAR(128) NOT NULL,
    RFC VARCHAR(32) NOT NULL,
    STATUS CHAR(1) DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_CUSTOMER;

INSERT INTO CUSTOMER(ID_CUSTOMER, NAME, FIRST_NAME, SECOND_NAME, BUSINESS_NAME, PHONE, ADDRESS, RFC, STATUS)
VALUES (SEQ_CUSTOMER.NEXTVAL, 'Limhi', 'Navarro', 'Aviles', 'Limhi SA de CV', '5534848438', 'Dolores Guerrero 210 A CTM Culhuacan Seccion 8 CDMX','NAAL951222TT9', 1);

-- COMMIT;

SELECT * FROM CUSTOMER;

ALTER TABLE CUSTOMER DROP COLUMN SECOND_NAME;
ALTER TABLE CUSTOMER DROP COLUMN BUSINESS_NAME;

ALTER TABLE CUSTOMER RENAME COLUMN FIRST_NAME TO LAST_NAME;

-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

CREATE TABLE ARTICLE(
    ID_ARTICLE NUMERIC(6) NOT NULL PRIMARY KEY,
    TRADEMARK VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(128) NOT NULL,
    PRICE NUMERIC(6,2) NOT NULL,
    STOCK NUMERIC(6,2) NOT NULL,
    STATUS CHAR(1) DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_ARTICLE;

INSERT INTO ARTICLE(ID_ARTICLE, TRADEMARK, DESCRIPTION, PRICE, STOCK) VALUES(SEQ_ARTICLE.NEXTVAL, 'Logitech', 'Teclado mecanico', 2000.99, 20);
INSERT INTO ARTICLE(ID_ARTICLE, TRADEMARK, DESCRIPTION, PRICE, STOCK) VALUES(SEQ_ARTICLE.NEXTVAL, 'Logitech', 'Mouse gamer', 700.99, 20);
INSERT INTO ARTICLE(ID_ARTICLE, TRADEMARK, DESCRIPTION, PRICE, STOCK) VALUES(SEQ_ARTICLE.NEXTVAL, 'Logitech', 'Bocinas G560', 2500.99, 20);
INSERT INTO ARTICLE(ID_ARTICLE, TRADEMARK, DESCRIPTION, PRICE, STOCK) VALUES(SEQ_ARTICLE.NEXTVAL, 'Logitech', 'Teclado', 200.99, 20);
INSERT INTO ARTICLE(ID_ARTICLE, TRADEMARK, DESCRIPTION, PRICE, STOCK) VALUES(SEQ_ARTICLE.NEXTVAL, 'Logitech', 'Mouse', 200.99, 20);
INSERT INTO ARTICLE(ID_ARTICLE, TRADEMARK, DESCRIPTION, PRICE, STOCK) VALUES(SEQ_ARTICLE.NEXTVAL, 'BenQ', 'Monitor 24', 7500.99, 20);
INSERT INTO ARTICLE(ID_ARTICLE, TRADEMARK, DESCRIPTION, PRICE, STOCK) VALUES(SEQ_ARTICLE.NEXTVAL, 'BenQ', 'Monitor 26 HDRi', 9500.99, 20);

-- COMMIT;

SELECT * FROM ARTICLE;

-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

CREATE TABLE ORDERS(
    ID_ORDER NUMERIC(6) NOT NULL PRIMARY KEY,
    ID_CUSTOMER NUMERIC(6) REFERENCES CUSTOMER(ID_CUSTOMER),
    TOTAL NUMERIC(9,2) NOT NULL,
    DESCRIPTION VARCHAR(128) NULL,
    ORDER_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_ORDER;

INSERT INTO ORDERS(ID_ORDER, ID_CUSTOMER, TOTAL, DESCRIPTION)
VALUES (SEQ_ORDER.NEXTVAL, 21, 6950, 'orden demo!');
INSERT INTO ORDERS(ID_ORDER, ID_CUSTOMER, TOTAL, DESCRIPTION)
VALUES (SEQ_ORDER.NEXTVAL, 41, 8000, 'orden demo 2!');

SELECT * FROM ORDERS;

-- COMMIT;

-- |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

CREATE TABLE ORDERS_DETAIL(
    ID_ORDER_DETAIL NUMERIC(6) NOT NULL PRIMARY KEY,
    ID_ORDER NUMERIC(6) REFERENCES ORDERS(ID_ORDER),
    ID_ARTICLE NUMERIC(6) REFERENCES ARTICLE(ID_ARTICLE),
    PRICE NUMERIC(6,2) NOT NULL,
    QUANTITY NUMERIC(6) NOT NULL,
    SUB_TOTAL NUMERIC(9,2) NOT NULL,
    STATUS CHAR(1) DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_ORDERS_DETAIL;

INSERT INTO ORDERS_DETAIL (ID_ORDER_DETAIL, ID_ORDER, ID_ARTICLE, PRICE, QUANTITY, SUB_TOTAL)
VALUES (SEQ_ORDERS_DETAIL.NEXTVAL, 1, 1, 2000.99, 2, 4001.98);
INSERT INTO ORDERS_DETAIL (ID_ORDER_DETAIL, ID_ORDER, ID_ARTICLE, PRICE, QUANTITY, SUB_TOTAL)
VALUES (SEQ_ORDERS_DETAIL.NEXTVAL, 2, 2, 700.99, 1, 700.99);
INSERT INTO ORDERS_DETAIL (ID_ORDER_DETAIL, ID_ORDER, ID_ARTICLE, PRICE, QUANTITY, SUB_TOTAL)
VALUES (SEQ_ORDERS_DETAIL.NEXTVAL, 2, 3, 2500.99, 1, 2500.99);

-- COMMIT;

SELECT * FROM ORDERS_DETAIL;